from .animal import Animal
from .anaconda import Anaconda
from .bass import Bass
from .chicken import Chicken
from .copperhead import CopperHead
from .coralsnake import CoralSnake
from .cow import Cow
from .duck import Duck
from .gardensnake import GardenSnake
from .goat import Goat
from .goose import Goose
from .horse import Horse
from .llama import Llama
from .rattlesnake import RattleSnake
from .swan import Swan
from .turtle import Turtle
